#!/usr/bin/sh

getent group greetd > /dev/null || groupadd -r -g 995 greetd 
getent passwd greetd > /dev/null || useradd -r -u 995 -g greetd -c "Greetd Greeter Account" -d /var/lib/greetd -s /usr/sbin/nologin greetd
